[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Artyom <worldbeater-dev@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.0.2"
Jinja2 = "^3.0.3"
SQLAlchemy = "^1.4.29"
Flask-JWT-Extended = "^4.3.1"
Flask-WTF = "^1.0.0"
email-validator = "^1.1.3"
alembic = "^1.7.5"
psycopg2-binary = "^2.9.3"
Flask-Bcrypt = "^0.7.1"
radon = "^5.1.0"
waitress = "^2.0.0"

[tool.poetry.dev-dependencies]
beautifulsoup4 = "^4.10.0"
pre-commit = "2.15.0"
isort = "5.9.3"
editorconfig-checker = "2.3.54"
pep8-naming = "0.12.1"
flake8 = "3.9.2"
flake8-flask = "0.9.3"
flake8-commas = "2.0.0"
flake8-docstrings = "1.6.0"
flake8-multiline-containers = "0.0.18"
flake8-polyfill = "1.0.2"
flake8-quotes = "3.3.0"
flake8-variables-names = "0.0.4"
pytest = "7.0.1"
pytest-cov = "3.0.0"
pytest-flask = "1.2.0"
pytest-alembic = "0.7.0"
greenlet = "1.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
